/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Banana by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/ahOO6wz8sV0)
 */
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useExplode } from '../hooks/useExplode';

const Banana = (props) => {
  const { nodes, materials } = useGLTF('/models/banana.glb');
  const group = useRef();

  useExplode(group, { distance: 6 });

  return (
    <group {...props} ref={group}>
      <group name="origin" scale={0.074}>
        <mesh
          name="pasted__pCube11_group_1"
          geometry={nodes.pasted__pCube11_group_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="pasted__pCube11_group_1_1"
          geometry={nodes.pasted__pCube11_group_1_1.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell" position={[0.455, -1.411, 0.108]}>
        <mesh
          name="banana_cell039"
          geometry={nodes.banana_cell039.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell039_1"
          geometry={nodes.banana_cell039_1.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        name="banana_cell001"
        geometry={nodes.banana_cell001.geometry}
        material={materials.blinn10SG}
        position={[0.081, 3.836, 2.447]}
      />
      <group name="banana_cell002" position={[-0.281, 2.788, 1.279]}>
        <mesh
          name="banana_cell001_1"
          geometry={nodes.banana_cell001_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell001_2"
          geometry={nodes.banana_cell001_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        name="banana_cell003"
        geometry={nodes.banana_cell003.geometry}
        material={materials.blinn10SG}
        position={[-0.081, 3.837, 2.448]}
      />
      <group name="banana_cell004" position={[0.323, -2.335, 0.782]}>
        <mesh
          name="banana_cell003_1"
          geometry={nodes.banana_cell003_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell003_2"
          geometry={nodes.banana_cell003_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell005" position={[-0.086, 3.61, 2.142]}>
        <mesh
          name="banana_cell004_1"
          geometry={nodes.banana_cell004_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell004_2"
          geometry={nodes.banana_cell004_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell006" position={[-0.143, 3.293, 1.799]}>
        <mesh
          name="banana_cell005_1"
          geometry={nodes.banana_cell005_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell005_2"
          geometry={nodes.banana_cell005_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell007" position={[0.284, 3.093, 0.939]}>
        <mesh
          name="banana_cell006_1"
          geometry={nodes.banana_cell006_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell006_2"
          geometry={nodes.banana_cell006_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell008" position={[-0.138, -2.694, 1.152]}>
        <mesh
          name="banana_cell007_1"
          geometry={nodes.banana_cell007_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell007_2"
          geometry={nodes.banana_cell007_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell009" position={[0.08, 3.613, 2.167]}>
        <mesh
          name="banana_cell008_1"
          geometry={nodes.banana_cell008_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell008_2"
          geometry={nodes.banana_cell008_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        name="banana_cell010"
        geometry={nodes.banana_cell010.geometry}
        material={materials.blinn10SG}
        position={[0.083, 3.976, 2.389]}
      />
      <group name="banana_cell011" position={[-0.085, 3.784, 2.158]}>
        <mesh
          name="banana_cell010_1"
          geometry={nodes.banana_cell010_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell010_2"
          geometry={nodes.banana_cell010_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell012" position={[-0.415, -1.122, 0.599]}>
        <mesh
          name="banana_cell011_1"
          geometry={nodes.banana_cell011_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell011_2"
          geometry={nodes.banana_cell011_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell013" position={[0.189, -2.586, 1.341]}>
        <mesh
          name="banana_cell012_1"
          geometry={nodes.banana_cell012_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell012_2"
          geometry={nodes.banana_cell012_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell014" position={[-0.319, 3.037, 0.84]}>
        <mesh
          name="banana_cell013_1"
          geometry={nodes.banana_cell013_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell013_2"
          geometry={nodes.banana_cell013_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell015" position={[0.171, -2.897, 1.329]}>
        <mesh
          name="banana_cell014_1"
          geometry={nodes.banana_cell014_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell014_2"
          geometry={nodes.banana_cell014_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell016" position={[-0.117, -2.839, 1.554]}>
        <mesh
          name="banana_cell015_1"
          geometry={nodes.banana_cell015_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell015_2"
          geometry={nodes.banana_cell015_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell017" position={[-0.139, 3.461, 1.667]}>
        <mesh
          name="banana_cell016_1"
          geometry={nodes.banana_cell016_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell016_2"
          geometry={nodes.banana_cell016_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell018" position={[-0.323, 2.127, 0.206]}>
        <mesh
          name="banana_cell017_1"
          geometry={nodes.banana_cell017_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell017_2"
          geometry={nodes.banana_cell017_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell019" position={[-0.323, -2.241, 0.64]}>
        <mesh
          name="banana_cell018_1"
          geometry={nodes.banana_cell018_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell018_2"
          geometry={nodes.banana_cell018_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell020" position={[0.404, 1.395, 0.639]}>
        <mesh
          name="banana_cell019_1"
          geometry={nodes.banana_cell019_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell019_2"
          geometry={nodes.banana_cell019_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell021" position={[-0.182, -2.555, 1.432]}>
        <mesh
          name="banana_cell020_1"
          geometry={nodes.banana_cell020_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell020_2"
          geometry={nodes.banana_cell020_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        name="banana_cell022"
        geometry={nodes.banana_cell022.geometry}
        material={materials.blinn10SG}
        position={[-0.01, 3.984, 2.528]}
      />
      <group name="banana_cell023" position={[0.422, 1.99, 0.201]}>
        <mesh
          name="banana_cell022_1"
          geometry={nodes.banana_cell022_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell022_2"
          geometry={nodes.banana_cell022_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <mesh
        name="banana_cell024"
        geometry={nodes.banana_cell024.geometry}
        material={materials.blinn10SG}
        position={[-0.086, 3.97, 2.391]}
      />
      <group name="banana_cell025" position={[-0.154, -2.935, 1.462]}>
        <mesh
          name="banana_cell024_1"
          geometry={nodes.banana_cell024_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell024_2"
          geometry={nodes.banana_cell024_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell026" position={[0.272, -2.121, 1.132]}>
        <mesh
          name="banana_cell025_1"
          geometry={nodes.banana_cell025_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell025_2"
          geometry={nodes.banana_cell025_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell027" position={[-0.407, 0.109, -0.135]}>
        <mesh
          name="banana_cell026_1"
          geometry={nodes.banana_cell026_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell026_2"
          geometry={nodes.banana_cell026_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell028" position={[-0.036, 0.233, 0.605]}>
        <mesh
          name="banana_cell027_1"
          geometry={nodes.banana_cell027_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell027_2"
          geometry={nodes.banana_cell027_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell029" position={[-0.409, -1.302, 0.057]}>
        <mesh
          name="banana_cell028_1"
          geometry={nodes.banana_cell028_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell028_2"
          geometry={nodes.banana_cell028_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell030" position={[0.307, 2.793, 1.264]}>
        <mesh
          name="banana_cell029_1"
          geometry={nodes.banana_cell029_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell029_2"
          geometry={nodes.banana_cell029_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell031" position={[0.076, 3.797, 2.176]}>
        <mesh
          name="banana_cell030_1"
          geometry={nodes.banana_cell030_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell030_2"
          geometry={nodes.banana_cell030_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell032" position={[-0.406, 1.493, 0.658]}>
        <mesh
          name="banana_cell031_1"
          geometry={nodes.banana_cell031_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell031_2"
          geometry={nodes.banana_cell031_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell033" position={[-0.285, -2.112, 1.152]}>
        <mesh
          name="banana_cell032_1"
          geometry={nodes.banana_cell032_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell032_2"
          geometry={nodes.banana_cell032_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell034" position={[0.386, -0.959, 0.654]}>
        <mesh
          name="banana_cell033_1"
          geometry={nodes.banana_cell033_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell033_2"
          geometry={nodes.banana_cell033_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell035" position={[0.094, -2.823, 1.552]}>
        <mesh
          name="banana_cell034_1"
          geometry={nodes.banana_cell034_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell034_2"
          geometry={nodes.banana_cell034_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell036" position={[0.139, 3.453, 1.648]}>
        <mesh
          name="banana_cell035_1"
          geometry={nodes.banana_cell035_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell035_2"
          geometry={nodes.banana_cell035_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell037" position={[0.13, 3.262, 1.796]}>
        <mesh
          name="banana_cell036_1"
          geometry={nodes.banana_cell036_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell036_2"
          geometry={nodes.banana_cell036_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
      <group name="banana_cell038" position={[0.388, 0.151, -0.022]}>
        <mesh
          name="banana_cell037_1"
          geometry={nodes.banana_cell037_1.geometry}
          material={materials.blinn10SG}
        />
        <mesh
          name="banana_cell037_2"
          geometry={nodes.banana_cell037_2.geometry}
          material={materials.blinn2SG}
        />
      </group>
    </group>
  );
};

useGLTF.preload('/models/banana.glb');

export default Banana;
