/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { DissolveMaterial } from './DissolveMaterial';

export default function Chair(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/chair-wood/model.gltf'
  );
  return (
    <group ref={group} {...props} dispose={null} position-y={-1}>
      <mesh geometry={nodes.chair.geometry}>
        <DissolveMaterial
          baseMaterial={materials['BrownDark.052']}
          visible={props.dissolveVisible}
          onFadeOut={props.onFadeOut}
          color="#7f532f"
        />
      </mesh>
    </group>
  );
}

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/chair-wood/model.gltf'
);
